#!/usr/bin/env bash
# setup.sh — first-time setup for the OpenClaw Docker stack.
#
# * Ensures a `.env` file exists (seeded from `.env.example` if missing).
# * Creates per-agent data directories so compose bind mounts succeed.
# * Reports missing prerequisites instead of continuing silently.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

cd "${ROOT_DIR}"

AGENTS=(architect designer developer qc operator pa)

if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: docker is not installed or not on PATH." >&2
  exit 1
fi

if ! docker compose version >/dev/null 2>&1 && ! command -v docker-compose >/dev/null 2>&1; then
  echo "ERROR: neither 'docker compose' nor 'docker-compose' is available." >&2
  echo "Install the Docker Compose plugin or the legacy docker-compose binary." >&2
  exit 1
fi

if [[ ! -f .env ]]; then
  cp .env.example .env
  echo "Created .env from .env.example — OPENCLAW_GATEWAY_TOKEN is generated by onboarding on first run; leave blank or paste an existing token."
else
  # Migrate any legacy `OPENCLAW_PULL_POLICY=missing` / `if_not_present`
  # values left over from the old compose-driven pull_policy setup. The
  # script-driven replacement only understands `always` or `never`.
  if grep -Eq '^OPENCLAW_PULL_POLICY=(missing|if_not_present)\s*$' .env; then
    tmp=".env.tmp.$$"
    sed -E 's/^OPENCLAW_PULL_POLICY=(missing|if_not_present)\s*$/OPENCLAW_PULL_POLICY=always/' .env >"${tmp}"
    mv "${tmp}" .env
    echo "Migrated legacy OPENCLAW_PULL_POLICY value in .env to 'always'."
    echo "  (Compose schemas differ on 'missing' vs 'if_not_present'; the stack now handles pulling from scripts/start.sh.)"
  fi

  # Migrate the old placeholder `OPENCLAW_IMAGE=your-openclaw-image:latest`
  # left over from earlier templates. That value is not a real image and
  # causes `docker compose pull` to fail with `pull access denied for
  # your-openclaw-image`. Replace it with the official GHCR image. We only
  # touch this exact placeholder so any custom / pinned image the user set
  # is preserved.
  if grep -Eq '^OPENCLAW_IMAGE=[[:space:]]*your-openclaw-image:latest[[:space:]]*$' .env; then
    tmp=".env.tmp.$$"
    sed -E 's|^OPENCLAW_IMAGE=[[:space:]]*your-openclaw-image:latest[[:space:]]*$|OPENCLAW_IMAGE=ghcr.io/openclaw/openclaw:latest|' .env >"${tmp}"
    mv "${tmp}" .env
    echo "Migrated legacy OPENCLAW_IMAGE placeholder in .env to 'ghcr.io/openclaw/openclaw:latest'."
    echo "  (The old template shipped a 'your-openclaw-image:latest' placeholder that is not a real image."
    echo "   Set OPENCLAW_IMAGE explicitly in .env if you want a different tag or a locally-built image.)"
  fi
fi

for agent in "${AGENTS[@]}"; do
  mkdir -p "data/${agent}"
  mkdir -p "config/${agent}"
done

echo "Setup complete. Next steps:"
echo "  1. Review .env (defaults use ghcr.io/openclaw/openclaw:latest; OPENCLAW_GATEWAY_TOKEN is generated by onboarding)."
echo "  2. ./scripts/start.sh"
